---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db-data-volume
          persistentVolumeClaim:
            claimName: db-data-pvc
      containers:
        - name: db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: vapor_username
            - name: POSTGRES_PASSWORD
              value: vapor_password
            - name: POSTGRES_DB
              value: vapor_database
          volumeMounts:
            - name: db-data-volume
              mountPath: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: vehicle:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DATABASE_HOST
              value: db-service
            - name: DATABASE_NAME
              value: vapor_database
            - name: DATABASE_USERNAME
              value: vapor_username
            - name: DATABASE_PASSWORD
              value: vapor_password
          command: ["./Vehicle"]
          args: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: vehicle:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DATABASE_HOST
              value: db-service
            - name: DATABASE_NAME
              value: vapor_database
            - name: DATABASE_USERNAME
              value: vapor_username
            - name: DATABASE_PASSWORD
              value: vapor_password
            - name: VEHICLE_SERVICE_HOST
              value: app-service
            - name: VEHICLE_SERVICE_PORT
              value: "8080"
          command: ["./Webhook"]
          args: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8081"]

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  selector:
    app: webhook
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort

---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z db-service 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: migrate
          image: vehicle:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DATABASE_HOST
              value: db-service
            - name: DATABASE_NAME
              value: vapor_database
            - name: DATABASE_USERNAME
              value: vapor_username
            - name: DATABASE_PASSWORD
              value: vapor_password
          command: ["./Vehicle"]
          args: ["migrate", "--yes"]
      restartPolicy: Never
  backoffLimit: 0

---
apiVersion: batch/v1
kind: Job
metadata:
  name: revert-job
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z db-service 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: revert
          image: vehicle:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DATABASE_HOST
              value: db-service
            - name: DATABASE_NAME
              value: vapor_database
            - name: DATABASE_USERNAME
              value: vapor_username
            - name: DATABASE_PASSWORD
              value: vapor_password
          command: ["./Vehicle"]
          args: ["migrate", "--revert", "--yes"]
      restartPolicy: Never
  backoffLimit: 0
